### ISSUE TITLE
Build broken/instructions?

### ISSUE THREAD

**Issue by whaleyr** [PharmGKB/genome-sequence-io#1]
I tried cloning and doing a "gradle jar" and I got a .jar of the manifest file and that's it.

Can you include build instructions in your README.md? Also, let me know if I'm doing something wrong or the build is broken?

**Comment by dmyersturnbull** [comment]
Use `jarAll` or `:xxx:jar`, where `xxx` is the name of the subproject (e.g. `gradle :core:jar`)

I'll add it to the readme.

**Comment by whaleyr** [comment]
Excellent, `jarAll` worked for me. Thanks
